### PR TITLE
Minor updates

### PR DESCRIPTION
**Pull request by Goooler**
We can kick these things by enabling @renovate-bot and keep this repo up to date.

### CODE REVIEW

**Comment by Goooler** [comment]
I'm trying to upgrade Gradle 8 for this project, will send a PR after finishing that.

**Comment by ysb33r** [comment]
> I'm trying to upgrade Gradle 8 for this project, will send a PR after finishing that.

If you can get it to work, great, but the requirement is that the plugin suite has to  compatible with a minimum of Gradle 7.0.2

**Comment by Goooler** [comment]
I bumped it to Gradle 7.6 first, but 1 test failed, I'm not sure why, see
- https://github.com/Goooler/asciidoctor-gradle-plugin/pull/43
- https://scans.gradle.com/s/pebpcysnv2ne6/tests/overview?outcome=FAILED

**Comment by ysb33r** [comment]
> I bumped it to Gradle 7.6 first, but 1 test failed, I'm not sure why, see
> 
>     * [Gradle 7.6.3 Goooler/asciidoctor-gradle-plugin#43](https://github.com/Goooler/asciidoctor-gradle-plugin/pull/43)
> 
>     * https://scans.gradle.com/s/pebpcysnv2ne6/tests/overview?outcome=FAILED

It probably has to do with how properties are interpreted. If you change the `'Can generate a asciidoctorconfigfile'` test in `AsciidoctorEditorConfigIntegrationSpec` to rather contain the following, I think it will work

```groovy
        attrFile.text = ":${key3}: ${value3}\n"

        new File(projectDir,'gradle.properties').text = """
        group=${groupName}
        version=${projVer}
        """.stripIndent()
        
        getGroovyBuildFile("""
        apply plugin : 'org.asciidoctor.jvm.base'
```

**Comment by Goooler** [comment]
It works! Addressing the update to #704.

**Pull request merged**
