### PR TITLE
Migrate branch `development-3.x`to Antora

### PR DESCRIPTION
**Pull request by abelsromero**
**This PR is for development-3.x branch**

Tried to keep changes to minimal. For example I have kept anchors instead of using `navtitle`.

In summary this PR contains
* Create Antora descriptors and modules (ROOT & appendices)
* Adjusted docs to start with section level 1
* Fix missing attributes:
    groovydoc-jvm -> removed, was not used.
    asciidoctor-docs -> Fixed docs urls that were pointing to old site. Created new asciidoc-url attribute.
    groovy-dsl-name -> replaced by groovy-dsl-name.
    kotlin-dsl, asciidoctorj-leanpub-name -> not defined, added text directly since only appears once.
    plugin-jvm, plugin-base -> content was been copied into partials because is not possible to include contents from outside modules.
* Fix cross references
* Removed pipeline and gradle configurations related to docs generation/publication to gh-pages.

* Other fixes:
    Removed unnecessary [appendix]

rel #433

### CODE REVIEW

**Comment by abelsromero** [comment]
Docs preview https://deploy-preview-66--asciidoctor-docs.netlify.app/home/

**Comment by abelsromero** [comment]
Could not reproduce the appveyor error in another Windows

**Comment by mojavelinux** [comment]
Do we even need the AppVeyor build anymore?

**Comment by ysb33r** [comment]
> Do we even need the AppVeyor build anymore?

No. We can kill it off now.

**Comment by abelsromero** [comment]
> No. We can kill it off now.

Removed.

Also squashed the changes.

**Comment by abelsromero** [comment]
Ping :%

**Comment by abelsromero** [comment]
I got permissions to merge, so this is on me now. I need to review what I did and ensure the version `version: '3.x-dev'` is correct.

**Comment by ysb33r** [comment]
We are going to 4.x now. Maybe you want to update this.

**Comment by ysb33r** [comment]
@abelsromero Do you want to modify this to rather merge against development-4.x?

**Comment by abelsromero** [comment]
Close this, I've been thinking on and off about this and I am inclined to move to a "per branch" model so unify how we have the configuration for other projects. We can discuss this after v4 release.

**Comment by ysb33r** [comment]
Closed as per @abelsromero

**Pull request closed without merging**
