### PR TITLE
Add integration tests.

### PR DESCRIPTION
**Pull request by pledbrook**
Implements #180. The integration tests are formed of a dedicated source set
called 'intTest'. They use the new Gradle TestKit to execute test builds in a
variety of scenarios for the plugin.

I've gone for a separate source set because they execute much more slowly than
normal unit tests. Nor can they be run directly from the IDE as unit tests: you
have to execute the `intTest` task for them to run correctly.

### CODE REVIEW

**Comment by pledbrook** [comment]
I refuse to take responsibility for the build failing on OpenJDK 7 :smile:

**Comment by pledbrook** [comment]
One change we should add to this pull request is an upgrade to Gradle 2.10 or higher. What do you think?

**Comment by ysb33r** [comment]
Go to 2.10.

**Comment by aalmiray** [comment]
Agreed on 2.10

**Comment by aalmiray** [comment]
Manually merged with https://github.com/asciidoctor/asciidoctor-gradle-plugin/commit/60cd5fa40616de4ba4b085e0e4089db9aa9de309

**Pull request merged**
