### PR TITLE
resolves #509 requires must guarantee order

### LINKED ISSUE #509: requires should use a List not a Set to guarantee order
> The Set interface does not provide any ordering guarantees.

https://docs.oracle.com/javase/6/docs/api/java/util/Set.html

The order in the `requires` list is important.
For instance, consider the following definition:

```gradle
asciidoctorj {
  requires 'rouge'
  requires "${rootProject.projectDir}/extensions/rouge_cypher_lexer.rb"
}
```

In this example, the `rouge` library must be required before the `rouge_cypher_lexer.rb` otherwise the following exception is thrown:

```
Exception in thread "main" org.jruby.exceptions.NameError: (NameError) uninitialized constant Rouge::Lexers
at org.jruby.RubyModule.const_missing(org/jruby/RubyModule.java:3747)
at RUBY.<main>(/path/to/training/modules/demo/build/.asciidoctorGems/gems/rouge-3.13.0/lib/rouge.rb:55)
at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1814)
at RUBY.<main>(/path/to/training/modules/demo/build/.asciidoctorGems/gems/rouge-3.13.0/lib/rouge.rb:55)
at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:978)
at RUBY.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:130)
at RUBY.<main>(/path/to/training/resources/extensions/rouge_cypher_lexer.rb:3)
at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:978)
at RUBY.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:117)
at RUBY.<main>(<script>:1)
``` 

Please note that this bug is hard to reproduce because sometimes it does works and sometimes it doesn't work.

### PR DESCRIPTION
**Pull request by Mogztter**
resolves #509

### CODE REVIEW

**Comment by ysb33r** [comment]
It looks good. Even though this technically break binary API, I don't think it will affect anyone. 

Can you set the PR against `development-3.x`. In this way it is a lot easier to line up all of the changes for the next release.

**Comment by Mogztter** [comment]
Oh right, master is now `4.x`?

**Comment by Mogztter** [comment]
> Can you set the PR against development-3.x. In this way it is a lot easier to line up all of the changes for the next release.

Done :+1:

**Comment by ysb33r** [comment]
> Oh right, master is now `4.x`?

Master is now 3.x released

**Comment by Mogztter** [comment]
I don't quite understand the branching strategy 🤪
But I think we are on the same page, this is a bug fix and it should be released in a bugfix version (probably 3.0.1) right?

For reference I'm using the following branching strategy:

- master: latest development (next major release)
- N.x: maintenance branch (bug fixes and features for version N)

**Comment by ysb33r** [comment]
> I don't quite understand the branching strategy 🤪
> But I think we are on the same page, this is a bug fix and it should be released in a bugfix version (probably 3.0.1) right?
> 
> For reference I'm using the following branching strategy:
> 
>     * master: latest development (next major release)
> 
>     * N.x: maintenance branch (bug fixes and features for version N)

What we normally do in this project is:
- `master` represents whatever is released.
- `maintenance-[12].x` represents maintenance branches for older releases in case we still need to do a release there. In this case a PR is made to the branch and the release is done from there.
- For current development we merge features into `development-3.x` and then when ready to release we merge all of those into `master` and perform the release.
- For urgent hotfixes, merge straight to `master` and then we do the release.

Currently @andres does all of the release work, becasue he ahs the key to push to the Gradle PLugin Portal. Once you get GH actions to work, we could automate the release by substituting a secret environmental variable containing the key for the Gradle plugin portal.

**Comment by Mogztter** [comment]
Ok, it makes sense.

> Currently @andres does all of the release work, becasue he ahs the key to push to the Gradle PLugin Portal. Once you get GH actions to work, we could automate the release by substituting a secret environmental variable containing the key for the Gradle plugin portal.

Yes that would be great 👍 
Speaking of GitHub actions, I think the pull request is ready for review. I think we should add more features once it's merged on master (add an automated release process, remove Travis, run more tests...)

> For urgent hotfixes, merge straight to master and then we do the release.

I think this bug is pretty annoying because the behavior is undefined (so you have a "random" bug) and as far as I know there's no practical workaround.
I'm surprised this bug was not found earlier maybe because it's "random".

**Comment by andres** [comment]
wrong @andres, just in case,

**Comment by Mogztter** [comment]
> wrong andres, just in case,

Ooops sorry about that! And thanks for the heads up :+1: 
:wave: @aalmiray

**Comment by Mogztter** [comment]
Thanks!

**Pull request merged**
