### PR TITLE
Adding Java 17 to the Github verification workflow

### PR DESCRIPTION
**Pull request by vogella**
Ensure that the plug-ins also is verified with Java 17.

### CODE REVIEW

**Comment by vogella** [comment]
Is Java 17 not yet supported?

**Comment by esafak** [comment]
Is the JDK 17 build working locally?

**Comment by vogella** [comment]
> Is the JDK 17 build working locally?

We use now Java 21,  works fine.

**Comment by vogella** [comment]
Closing. AFAICS the verification build uses an older version of Gradle which does not yet know how to handle Java 17 nor Java 21 and suggesting to change that seems out of scope for me, this is something for the main developers to decide.

**Pull request closed without merging**
