### PR TITLE
Preparations for 1.5.8 release

### PR DESCRIPTION
**Pull request by ysb33r**
Main items:
- Merge back changes from `master` that is not on `development`.
- AsciidoctorJ 1.5.7 is default version.
- Groovy DSL 1.0.0.Alpha3 is default extensions version.
- Hopefully deal with extensions disappearing.

### CODE REVIEW

**Comment by aalmiray** [comment]
My, my, I did not notice so many commits were made to `master` and skipped `development`. Thank you @ysb33r for having a look at this and porting over the changes 😄

**Comment by mojavelinux** [comment]
Nice work!

I noticed that the tag didn't get created for this release (which also happened for 1.5.7). Could you push it manually?

**Comment by mojavelinux** [comment]
I've been observing this split between development and master for several years now, and I can only conclude from observing the confusion that it does not work. What is the justification for it? Can we move to a simple master / release branch strategy? Master is where development for the current version line would be done. Release branches would either be used for old version lines or for future development (like the development-2.0 branch). The development branch is just confusing people.

**Comment by ysb33r** [comment]
> I noticed that the tag didn't get created for this release (which also happened for 1.5.7). Could you push it manually?

I'm note sure how @aalmiray did the release, but I added the release and tag manually.

**Comment by ysb33r** [comment]
> I've been observing this split between development and master for several years now, and I can only conclude from observing the confusion that it does not work. What is the justification for it? Can we move to a simple master / release branch strategy? Master is where development for the current version line would be done. Release branches would either be used for old version lines (1.5.x) or for future development (like the development-2.0 branch). The development branch is just confusing people.

I think I have to leave that up to @aalmiray to explain the reason.

One thin I've done with the projects that I have on GitLab (not GitHub) is not now have a release branch. Master is the one where everything is consoliated and merged to. For a release, master is merged to release and pushed. The release process is then automatic.

**Comment by mojavelinux** [comment]
> For a release, master is merged to release and pushed. The release process is then automatic.

That I can get behind. It's precisely what I do in Antora and it works great.

**Comment by ysb33r** [comment]
> I forgot to manually push the tags for 1.5.7 and 1.5.8.

I can reverse engineer the 1.5.7 tag

**Pull request merged**
