### PR TITLE
resolves #536 configure the failure level and fail the task accordingly

### LINKED ISSUE #536: Add an option to configure the failure level and fail the task accordingly
Asciidoctor can return a non-zero exit code if specified logging level is reached. For instance, it can be useful when you want to fail if an include directive is not found (by setting `failure_level` to `WARN`).

In the context of Gradle, I think we should probably throw an exception to fail the task.

I can submit a pull request with a few guidance on how to (properly) fail task.

### PR DESCRIPTION
**Pull request by Mogztter**
resolves #536

### CODE REVIEW

**Comment by Mogztter** [comment]
On my local workspace, I get the following exceptions:

```
Exception in thread "main" java.lang.NoClassDefFoundError: Lorg/asciidoctor/gradle/base/process/LoggerSeverity;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredField(Class.java:2068)
	at java.io.ObjectStreamClass.getDeclaredSUID(ObjectStreamClass.java:1803)
	at java.io.ObjectStreamClass.access$700(ObjectStreamClass.java:79)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:494)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:482)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:482)
	at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:379)
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:669)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1883)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1749)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2040)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1571)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
	at java.util.ArrayList.readObject(ArrayList.java:797)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1158)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2176)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2067)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1571)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2285)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2209)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2067)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1571)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
	at org.asciidoctor.gradle.remote.AsciidoctorJavaExec$_main_closure1$_closure7.doCall(AsciidoctorJavaExec.groovy:45)
	at org.asciidoctor.gradle.remote.AsciidoctorJavaExec$_main_closure1$_closure7.call(AsciidoctorJavaExec.groovy)
	at org.codehaus.groovy.runtime.IOGroovyMethods.withCloseable(IOGroovyMethods.java:1614)
	at org.asciidoctor.gradle.remote.AsciidoctorJavaExec$_main_closure1.doCall(AsciidoctorJavaExec.groovy:44)
	at org.asciidoctor.gradle.remote.AsciidoctorJavaExec$_main_closure1.call(AsciidoctorJavaExec.groovy)
	at org.codehaus.groovy.runtime.IOGroovyMethods.withStream(IOGroovyMethods.java:1191)
	at org.codehaus.groovy.runtime.ResourceGroovyMethods.withInputStream(ResourceGroovyMethods.java:1878)
	at org.asciidoctor.gradle.remote.AsciidoctorJavaExec.main(AsciidoctorJavaExec.groovy:43)
Caused by: java.lang.ClassNotFoundException: org.asciidoctor.gradle.base.process.LoggerSeverity
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

Do I need to declare this new class somewhere? :thinking:

**Comment by Mogztter** [comment]
I'm now using an `int`, since the `ExecutorConfiguration` can be serialized I think it's safer.

**Comment by Mogztter** [comment]
I still get a `Caused by: java.lang.NoClassDefFoundError: org.asciidoctor.gradle.base.process.LoggerSeverity` in `org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':asciidoctor-gradle-jvm:compileRemoteTestGroovy'.`. 

Any guidance would be greatly appreciated 😉

**Comment by Mogztter** [comment]
@ysb33r I Made some progress but I still get `NoClassDefFoundError: org.asciidoctor.gradle.base.process.LoggerSeverity`, so the question is should I add `asciidoctor-gradle-base` as a dependency or should I only use an `int` in "remote" module?

**Comment by Mogztter** [comment]
I've decided to use the `Severity` enum from AsciidoctorJ but maybe I need to duplicate the enum (similar to what we are doing with `SafeMode`) to not tightly coupled the Asciidoctor Gradle task configuration with AsciidoctorJ?

**Comment by Mogztter** [comment]
Build is (almost) green :tada: 

Travis is failing on `java.lang.IllegalArgumentException: Unsupported class file major version 57` but is it related?

**Comment by ysb33r** [comment]
The code looks good and the duplication was a good idea. At base level we cannot use anything from AsciidoctorJ. This can only be done once we get done do the packages that actually are JVM dependent. (Otherwise we introduce bad dependencies for Asiidoctor.js execution).

Also an important point to remember is that anuthing in the  `*.remote.*` packages cannot use anything from the plugin itself. It is purely dependent on AsciidoctorJ itself. Otherwise you will see the issues you saw at the beginning of missing classes.

**Comment by ysb33r** [comment]
> Build is (almost) green tada
> 
> Travis is failing on `java.lang.IllegalArgumentException: Unsupported class file major version 57` but is it related?

It seems that somewhere there is something that we introduced that only works with JDK11.

Can you add a matrix to the GitHub actions that also builds with JDK8. Then we'll know when it is a real issue or whether it is Travis playing up again.

**Comment by slonopotamus** [comment]
It fails because you're running [Java 13 on MacOS CI](https://travis-ci.org/github/asciidoctor/asciidoctor-gradle-plugin/jobs/668314908#L91).

**Comment by slonopotamus** [comment]
Commit 93e4bbc2bc2dcf329d13f453657d395bf5f87d27 wanted to drop Linux on Travis (dunno why) and only run MacOS. But intead, it says "run on linux with openjdk11 *AND* run on MacOS with default JDK".

**Comment by Mogztter** [comment]
> It fails because you're running Java 13 on MacOS CI.

Nice catch :+1: 

> But I'd just stop using Travis because you already have MacOS builds on GitHub Actions.

Yes, especially now that we run Java 8 + Java 11 on Linux (Ubuntu) and macOS on GitHub Actions. There's no more reason to keep Travis, right?

**Comment by ysb33r** [comment]
Yes. We can delete the Travis file.

⁣Get BlueMail for Android ​

**Comment by Mogztter** [comment]
I got a ` Caused by: org.gradle.cache.LockTimeoutException: Timeout waiting to lock jars (/tmp/.gradle-test-kit-runner/caches/jars-3). It is currently in use by another Gradle instance.`, I thought this issue was related to Windows but it was in Ubuntu with Java 8.

Restarting the CI as it's most likely an intermittent failure.

**Comment by Mogztter** [comment]
> Yes. We can delete the Travis file.

I've removed it, build is green 🎉

**Pull request merged**
