### PR TITLE
Upgrade grolifant to 1.0.1

### PR DESCRIPTION
**Pull request by pbielicki**
This change upgrades grolifant version to 1.0.1

### CODE REVIEW

**Comment by pbielicki** [comment]
https://scans.gradle.com/s/gezquzplkhkwu

I don't think these test failures are caused by my change

**Comment by pbielicki** [comment]
I checked - this test also fails in `master` https://scans.gradle.com/s/6bgwubymg6jpg/tests/failed

**Comment by pbielicki** [comment]
@aalmiray can you ptal?

**Comment by ysb33r** [comment]
I've changed the targetr branch to development-3.x. Will wait for pipeline to complete and then proceed to deal with errors.

**Comment by ysb33r** [comment]
We are upgrading to a later version of Grolifatn, so this is no longer needed.

**Pull request closed without merging**
